language: python
python:
  - "2.7"

branch:
    only:
        - master
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
# - py.test
    - py.test flask_databrowser/test/
notifications:
    email:
      recipients:
        - abc549825@163.com
        - xiechao06@gmail.com
